name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          git clone git@github.com:mahtat555/lblog.git
          cd lblog/
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install --ignore-platform-reqs
          php artisan key:generate
          php artisan storage:link
          chmod -R 777 storage bootstrap/cache
